---

all:
  hosts:
    localhost:

  children:
    # groups
    # ...

    # connection groups
    ansible_ssh_sudo:
      #hosts:
      #children:
    ansible_ssh_doas:
    ansible_winrm:

    root_ssh:
    admin_winrm:

# vim: set ft=yaml.ansible sw=2 ts=2 et colorcolumn=160 :
# eof
