---

all:
  hosts:
    localhost:

  children:
    # os groups
    freebsd:
      #hosts:

    linux:
      hosts:
        localhost:

    openbsd:
      #hosts:

    windows:
      #hosts:

    # more groups
    # ...

    # connection groups
    ansible_ssh_sudo:
      #hosts:
      #children:
    ansible_ssh_doas:
    ansible_winrm:

    root_ssh:
      children:
        linux:
    admin_winrm:

# vim: set ft=yaml.ansible sw=2 ts=2 et colorcolumn=160 :
# eof
